#!/usr/bin/env bash
source "$(dirname "$0")/../lib.sh"

brew_bin="/opt/homebrew/bin/brew"
[[ -x $brew_bin ]] || brew_bin="/usr/local/bin/brew"

if [[ -x $brew_bin ]]; then
	log "homebrew: already installed"
else
	log "homebrew: not installed, fetching"
	execute env NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL \
		https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

eval "$("$brew_bin" shellenv)"
