#!/usr/bin/env bash
source "$(dirname "$0")/../lib.sh"

# stop Finder from creating .DS_Store files on network shared and USB drives
execute defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
execute defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
execute killall Finder

# TODO: Add in dock position and autohide, other system defaults I want
